name: Session 11 run basic PW Tests on CI
on: workflow_dispatch
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
# schedule:
# - cron: '0 16 * * 3' # every Wednesday at 16:00 UTC - PH time Thursday 12:00 AM

env:
    SAUCEDEMO_USERNAME: ${{ secrets.SAUCE_USERNAME }}
    SAUCEDEMO_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
    
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run login-test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
